on: push
name: Terraform Lint
jobs:
  tf_lint:
    name: Terraform Lint
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Terraform Lint
        uses: kapost/terraform-linter@v1
        env:
          DISPLAY_DIFF: true # <-- Optional - used to display diff for terraform fmt command
